### ISSUE TITLE
Revert dropwizard version to 0.7

### ISSUE THREAD

**Issue by jklukas** [tkrille/dropwizard-template-config#23]
The listing for this project on http://modules.dropwizard.io/thirdparty/ indicates compatibility with DW 0.7 and 0.8.

The current version uses DW 0.9.1 in the pom, although it appears to still work compile and run just fine in 0.7.1 projects based on our experience.

The appearance of 0.9.1 in the pom caused some confusion about compatibility. Unless there's a reason for the newer version, I think we should revert to 0.7 in the pom and add a comment there stating that we're keeping it there to ensure compatibility, but the project is expected to work up through modern DW versions. We should also add a note in the docs and update the listing on the DW modules page to indicate 0.7 through 1.0.0 compatibility.

Any objections, @tkrille ?

This project is gaining more traction at Simple, which I'm really pleased to see, and which is bringing up this question 😄

**Comment by tkrille** [comment]
Hi @jklukas,

that's an interesting question you're bringing up here. When I started this project, the idea was to only officially support the latest version of Dropwizard. That's why we ended up with version 0.9.1 as dependency after all. Seems that I somehow missed Dropwizard 1.0.0 :) I've also noticed that the bundle seems to be compatible with all Dropwizard version since 0.7.1. I don't really know what the best practice is in the Dropwizard community, but your suggestion looks well thought out to me. We could also use [version ranges](http://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-project-dependencies.html#pom-relationships-sect-version-ranges). Then we would be very explicit about what versions the bundle supports. Someone just has to update the range from time to time :) What do you think of that?

PS: I'm very happy to hear, that this project is helping you to build amazing software. Thanks a lot! :)

**Comment by jklukas** [comment]
I had assumed that the Dropwizard dependency was marked with "provided"
scope for the purpose of letting the dependent application choose the
version, but I don't have a deep understanding of that. Maybe specifying an
explicit range is the right thing to do.

I'd like to avoid the need to make new point releases simply to update the
upper bound. I guess some experimentation may be in order. I wish I could
find a more authoritative reference about how to approach this situation
with maven.

**Comment by jklukas** [comment]
I just testing with a version range:
```
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>[0.7.1,)</version>
            <scope>provided</scope>
        </dependency>
```

This caused ALL dropwizard versions from 0.7.1 to present to be downloaded when I invoked maven to compile. This is undesirable behavior for maintainers. That, combined with the fact that I've never seen a version range actually used in another project, makes me think we should cross that option off the list.

It seems like the right thing to do is to set the dropwizard version to 0.7.1 and leave it marked with scope of `provided`. AFAICT, projects calling this dependency aren't even able to tell what version of dropwizard we compile with when dropwizard is a `provided`-scoped dependency. By keeping the version at 0.7.1, we ensure that we don't accidentally use a method introduced in a later version. If a new dropwizard feature eventually arrives that we want to take advantage of, we'd re-evaluate the minimum supported version.

I think I'm going to put together a PR that reduces the version to 0.7.1 and adds a comment about expected compatibility and the most recent version that we've tested with.

**Comment by tkrille** [comment]
Hi @jklukas,

thanks for trying out the version range thing. Too bad this doesn't work out as expected. I agree to your suggestion pinning the Dropwizard version to 0.7.1 and documenting the working version.

I always wanted to have some tests that actually start a Dropwizard app with the bundle. I will have a look if this is currently possible with the Dropwizard test tools.

**Comment by jklukas** [comment]
It would indeed be nice to have the test suite start up a Dropwizard app. Even better if we could run a test on each major version.

**Comment by tkrille** [comment]
Having multiple version would be really awesome. I'll create an issue for it. Maybe someone has the time to do it :) Meanwhile, I'm closing this issue here. It's solved, isn't it?
