### ISSUE TITLE
Add ability to supply custom EnvironmentProvider and SystemPropertiesProvider to TemplateConfigBundleConfiguration

### ISSUE THREAD

**Issue by bobtiernay-okta** [tkrille/dropwizard-template-config#26]
Currently this isn't possible as it's baked into `TemplateConfigBundle`

**Comment by tkrille** [comment]
Hi @bobtiernay-okta,

sorry for the late reply, but this project is actually not maintained anymore.

I wonder why you would want to do that. Instead, you should add a custom `TemplateConfigVariablesProvider`. Not being able to override environment variables or system properties is an intentional limitation. Btw: The only reason, that there are interfaces and default implementations for environment variable and system properties providers, is to make everything easier to test.
